defaults:
  - _self_
  - datamodule: google_commands.yaml
  - module: classification.yaml
  - trainer: default.yaml
  - logger: neptune.yaml

# task name, determines output directory path
task_name: "wake_voice_detection"

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True
save_state_dict: True

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 42

#Whether to use torch 2.0 compile function
compile: False


#Lightning checkpointing definition
checkpoints:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  save_top_k: 1
  monitor: val_acc
  mode: min
  dirpath: checkpoints
  filename: "${task_name}-{epoch}-{val_acc:.2f}"
