version: 2

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"

sphinx:
  fail_on_warning: true
