[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "audio_research_toolkit"
version = "0.0.1"
authors = [
  { name="GHOST", email="ghost@put.poznan.pl" },
]
description = "Audio Package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
  "datasets~=2.9.0",
  "numpy~=1.23.5",
  "lightning~=2.0",
  "torchaudio~=2.0.1",
  "torchmetrics~=0.11.0",
  "torch~=2.0.0",
  "hydra-core~=1.3.2"
]

[project.optional-dependencies]
dev = [
  "flake8~=6.0.0",
  "tox~=4.4.7",
  "pytest~=7.2.2",
  "pytest-cov~=4.0.0",
  "mypy~=1.1.1",
  "black~=23.1.0"
]

[project.urls]
"Homepage" = "https://github.com/pypa/audioresearchtoolkit"
"Bug Tracker" = "https://github.com/pypa/audioresearchtoolkit/issues"

[tool.pytest.ini_options]
addopts = "--cov=art"
testpaths = [
  "tests",
]

[tool.mypy]
mypy_path="art"
