_target_: art.similarity.data.EfficientWordNetOriginalDataModule
noise_chunked_path: WakeWordDetection/EfficientWord-Net/chunkedNoise
noise_path: WakeWordDetection/EfficientWord-Net/noise_files_format_fixed
words_path: WakeWordDetection/EfficientWord-Net/dataset_format_fixed
batch_size: 8
